DATA:
  DATASET: LVOT
  DATA_PATH: /home/ilkay/Documents/caner/datasets/mdai/create_lvot_dataset/jpg_slices
  IMG_SIZE: 224
MODEL:
  TYPE: resnet34
  NAME: resnet34_window8_224_22ktoLVOT_finetune_3xlr
  TORCHVISION_PRETRAINED: true
  DROP_PATH_RATE: 0.2
  SWIN:
    EMBED_DIM: 128
    DEPTHS: [ 2, 2, 18, 2 ]
    NUM_HEADS: [ 4, 8, 16, 32 ]
    WINDOW_SIZE: 8
TRAIN:
  EPOCHS: 60
  WARMUP_EPOCHS: 5
  WEIGHT_DECAY: 1e-8
  BASE_LR: 6e-05
  WARMUP_LR: 2e-08
  MIN_LR: 2e-07
