python -m torch.distributed.launch --nproc_per_node 1 --master_port=12345 main.py --cfg configs/LVOT/efficientnetb5_window7_224_22ktoLVOT_finetune_3xlr.yaml --batch-size 64 --accumulation-steps 2 --use-checkpoint --output=save/
python -m torch.distributed.launch --nproc_per_node 1 --master_port=12345 main.py --cfg configs/LVOT/efficientnetb4_window7_224_22ktoLVOT_finetune_3xlr.yaml --batch-size 64 --accumulation-steps 2 --use-checkpoint --output=save/
python -m torch.distributed.launch --nproc_per_node 1 --master_port=12345 main.py --cfg configs/LVOT/efficientnetb3_window7_224_22ktoLVOT_finetune_3xlr.yaml --batch-size 64 --accumulation-steps 2 --use-checkpoint --output=save/
python -m torch.distributed.launch --nproc_per_node 1 --master_port=12345 main.py --cfg configs/LVOT/efficientnetb2_window7_224_22ktoLVOT_finetune_3xlr.yaml --batch-size 64 --accumulation-steps 2 --use-checkpoint --output=save/
python -m torch.distributed.launch --nproc_per_node 1 --master_port=12345 main.py --cfg configs/LVOT/efficientnetb0_window7_224_22ktoLVOT_finetune_3xlr.yaml --batch-size 64 --accumulation-steps 2 --use-checkpoint --output=save/
python -m torch.distributed.launch --nproc_per_node 1 --master_port=12345 main.py --cfg configs/LVOT/efficientnetb1_window7_224_22ktoLVOT_finetune_3xlr.yaml --batch-size 64 --accumulation-steps 2 --use-checkpoint --output=save/
#python -m torch.distributed.launch --nproc_per_node 1 --master_port=12345 main.py --cfg configs/LVOT/resnet34_window7_224_22ktoLVOT_finetune_3xlr.yaml --batch-size 16 --test-batch-size 256 --accumulation-steps 8 --use-checkpoint --output=save/
#python -m torch.distributed.launch --nproc_per_node 1 --master_port=12345 main.py --cfg configs/LVOT/resnet50_window7_224_22ktoLVOT_finetune_3xlr.yaml --batch-size 16 --test-batch-size 256 --accumulation-steps 8 --use-checkpoint --output=save/
# python -m torch.distributed.launch --nproc_per_node 1 --master_port=12345 main.py --cfg configs/LVOT/resnet101_window7_224_22ktoLVOT_finetune_3xlr.yaml --batch-size 64  --accumulation-steps 2 --test-batch-size 256 --use-checkpoint --output=save/
# python -m torch.distributed.launch --nproc_per_node 1 --master_port=12345 main.py --cfg configs/LVOT/resnet152_window7_224_22ktoLVOT_finetune_3xlr.yaml --batch-size 64  --accumulation-steps 2 --test-batch-size 256 --use-checkpoint --output=save/
